/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        Student[] studentsLvl1 = {
            new Student("Упиров", "Владислав", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Безушко", "Марія", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Валуєв", "Олександр", "Б-000-24-1-ХЗ", "АКФ"),
            new Student("Барановський", "Артем", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Власюк", "Артем", "Б-111-24-1-АБ", "АКФ"),
        };

        System.out.println("Рівень 1: Сортування вставкою");
        System.out.println("До сортування:");
        for (Student s : studentsLvl1) System.out.println(s);
        insertionSort(studentsLvl1);
        System.out.println("\nПісля сортування:");
        for (Student s : studentsLvl1) System.out.println(s);

        Student[] studentsLvl2 = {
            new Student("Упиров", "Владислав", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Безушко", "Марія", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Валуєв", "Олександр", "Б-000-24-1-ХЗ", "АКФ"),
            new Student("Барановський", "Артем", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Власюк", "Артем", "Б-111-24-1-АБ", "АКФ"),
        };

        System.out.println("\nРівень 2: Сортування за індексами");
        System.out.println("До сортування:");
        for (Student s : studentsLvl2) System.out.println(s);
        sortByIndex(studentsLvl2);
        System.out.println("\nПісля сортування:");
        for (Student s : studentsLvl2) System.out.println(s);

        Student[] studentsLvl3 = {
            new Student("Упиров", "Владислав", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Безушко", "Марія", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Валуєв", "Олександр", "Б-000-24-1-ХЗ", "АКФ"),
            new Student("Барановський", "Артем", "Б-121-24-2-ПІ", "ФКНТ"),
            new Student("Власюк", "Артем", "Б-111-24-1-АБ", "АКФ"),
        };

        System.out.println("\nРівень 3: Пірамідальне сортування");
        System.out.println("До сортування:");
        for (Student s : studentsLvl3) System.out.println(s);
        heapSort(studentsLvl3);
        System.out.println("\nПісля сортування:");
        for (Student s : studentsLvl3) System.out.println(s);
    }

    // Метод сортування вставкою (Insertion Sort)
    public static void insertionSort(Student[] stud) {
        int size = stud.length;
        for (int i = 1; i < size; i++) {
            Student element = stud[i];
            int j = i - 1;
            // Сортування за прізвищем (алфавітний порядок)
            while (j >= 0 && (stud[j].surname.compareTo(element.surname) > 0)) {
                stud[j + 1] = stud[j];
                j--;
            }
            stud[j + 1] = element;
        }
    }

    // Метод сортування за індексами (Sort By Index)
    public static void sortByIndex(Student[] stud) {
        int size = stud.length;
        int[] index = new int[size];
        for (int i = 0; i < size; i++) {
            index[i] = i;
        }
        for (int i = 0; i < size; i++) {
            for (int j = i + 1; j < size; j++) {
                // Сортування за прізвищем
                if (
                    stud[index[i]].surname.compareTo(stud[index[j]].surname) > 0
                ) {
                    int temp = index[i];
                    index[i] = index[j];
                    index[j] = temp;
                }
            }
        }
        Student[] temp = new Student[size];
        for (int i = 0; i < size; i++) {
            temp[i] = stud[index[i]];
        }
        for (int i = 0; i < size; i++) {
            stud[i] = temp[i];
        }
    }

    // Метод пірамідального сортування (Heap Sort)
    public static void heapSort(Student[] stud) {
        int n = stud.length;

        // Побудова піраміди (перегрупування масиву)
        for (int i = n / 2 - 1; i >= 0; i--) {
            heapify(stud, n, i);
        }

        // Один за одним витягуємо елементи з піраміди
        for (int i = n - 1; i > 0; i--) {
            // Переміщуємо поточний корінь в кінець
            Student temp = stud[0];
            stud[0] = stud[i];
            stud[i] = temp;

            // Викликаємо heapify на зменшеній піраміді
            heapify(stud, i, 0);
        }
    }

    // Допоміжний метод для перетворення піддерева з вузлом i (індекс) в піраміду, n - розмір піраміди
    static void heapify(Student[] stud, int n, int i) {
        int largest = i; // Ініціалізуємо найбільший елемент як корінь
        int l = 2 * i + 1; // лівий = 2*i + 1
        int r = 2 * i + 2; // правий = 2*i + 2

        // Якщо лівий дочірній елемент більший за корінь (порівнюємо прізвища)
        if (l < n && stud[l].surname.compareTo(stud[largest].surname) > 0) {
            largest = l;
        }

        // Якщо правий дочірній елемент більший за найбільший на даний момент
        if (r < n && stud[r].surname.compareTo(stud[largest].surname) > 0) {
            largest = r;
        }

        // Якщо найбільший елемент не є коренем
        if (largest != i) {
            Student swap = stud[i];
            stud[i] = stud[largest];
            stud[largest] = swap;

            // Рекурсивно перетворюємо порушене піддерево в піраміду
            heapify(stud, n, largest);
        }
    }
}
